
import os

input_data = "input_data/{filename}.txt"
output_dir = "output"
ids, = glob_wildcards(input_data)

rule concatenate:
    input: expand(input_data, filename=ids)
    output: "{}/concatenated.txt".format(output_dir)
    shell:
        "cat {input} > {output}"

rule all:
    input: rules.concatenate.output
