
import os

input_data = "input_data/{id}.txt"
ids, = glob_wildcards(input_data)

rule concatenate:
    input: expand(input_data, id=ids)
    output: "output/concatenated.txt"
    shell:
        "cat {input} > {output}"

rule all:
    input: rules.concatenate.output
