
input_data = "input_data/{id}.txt"
ids, = glob_wildcards(input_data)

rule sort:
    input: "input_data/{id}.txt"
    output: "output/{id}.sorted.txt"
    shell:
        "sort {input} > {output}"

rule all:
    input: expand(rules.sort.output, id=ids)
