input_data = "input_data/{id}.txt"
ids, = glob_wildcards(input_data)

rule sort:
    input: "input_data/{id}.txt"
    output: "output/{id}.sorted.txt"
    shell:
        "sort {input} > {output}"

rule all:
    input: ["output/file1.sorted.txt", "output/file2.sorted.txt"]
